"""empty message

Revision ID: 3fea01c3fb39
Revises: 450e14f71ac1
Create Date: 2022-12-08 10:02:08.185459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fea01c3fb39'
down_revision = '450e14f71ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_list_items',
    sa.Column('grocery_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('grocery_item_id')
    )
    op.create_table('recipes',
    sa.Column('user_recipe_id', sa.Integer(), nullable=False),
    sa.Column('method_instructions', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_recipe_id')
    )
    op.create_table('meal_plans',
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('user_recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_recipe_id'], ['recipes.user_recipe_id'], ),
    sa.PrimaryKeyConstraint('meal_plan_id')
    )
    op.create_table('pantry_items',
    sa.Column('pantry_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=10), nullable=True),
    sa.Column('user_ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_ingredient_id'], ['user_ingredients.user_ingredient_id'], ),
    sa.PrimaryKeyConstraint('pantry_item_id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=10), nullable=True),
    sa.Column('user_recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['user_recipe_id'], ['recipes.user_recipe_id'], ),
    sa.PrimaryKeyConstraint('recipe_ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredients')
    op.drop_table('pantry_items')
    op.drop_table('meal_plans')
    op.drop_table('recipes')
    op.drop_table('grocery_list_items')
    # ### end Alembic commands ###
