"""empty message

Revision ID: 661f0c17474e
Revises: 3fea01c3fb39
Create Date: 2022-12-08 12:40:26.335132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661f0c17474e'
down_revision = '3fea01c3fb39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_name', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('recipe_name')

    # ### end Alembic commands ###
